# -*- coding: utf-8 -*-
"""TSF GRIP Task-3-EDA-RETAIL(DATA SCIENCE AND BUSSINESS ANALYTICS-JUNE2023)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iX_crzQ43vt00PUFQ4PPxDI6Rmd0al9M
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt  
# %matplotlib inline
from sklearn.linear_model import LinearRegression

data = pd.read_csv("/content/SampleSuperstore.csv")

data.shape

data.head(10)

data.isnull().sum()

data.isnull()

data.info()

data.info

data.describe

data.describe()

data.isna().any()

correlation=data.corr()
correlation

import seaborn as sns
sns.heatmap(data.corr(),annot=True,cmap='inferno')

data['City'].value_counts()

print(data["City"].unique())

data['Profit'].value_counts()

data['Ship Mode'].value_counts()

sns.barplot(x = 'Ship Mode',y = 'Quantity',data = data)
plt.show()

sns.barplot(x = 'City',y = 'Discount',data = data)
plt.show()

t1 = data['Region'].value_counts()[:150]
t1.plot(kind='bar',figsize=(10,8))
plt.title('Region')

print(data["Country"].unique())

print(data["Segment"].unique())

data['Segment'].value_counts()

s1 = data['Segment'].value_counts()[:150]
s1.plot(kind='pie',figsize=(10,8))
plt.title('Segment')

R1 = data['State'].value_counts()[:150]
R1.plot(kind='bar',figsize=(10,8))
plt.title('State')

c1 = data['City'].value_counts()[:150]
c1.plot(kind='pie',figsize=(10,8))
plt.title('City')

data['Sub-Category'].value_counts()

data['Sub-Category'].value_counts().sum()

data.cov()

data['Sub-Category'].value_counts().mean()

data['Segment'].value_counts().mean()